language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  nosetests -svd --logging-level=INFO --with-doctest --with-coverage --cover-package=apertools --where=apertools

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
